In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# import libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Reading data

In [5]:
data = pd.read_excel("/kaggle/input/datasets/mahmoudalimahmoud/customer-invoice/merged_output.xlsx")
df=data.copy()
df

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,...,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,InvoiceLineId,TrackId,UnitPrice,Quantity
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,531,3247,1.99,1
1,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,532,3248,1.99,1
2,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,649,447,0.99,1
3,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,650,449,0.99,1
4,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,651,451,0.99,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,59,Puja,Srivastava,NaN,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,+91 080 22289999,...,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,8.91,1537,2340,0.99,1
2236,59,Puja,Srivastava,NaN,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,+91 080 22289999,...,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,8.91,1538,2346,0.99,1
2237,59,Puja,Srivastava,NaN,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,+91 080 22289999,...,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,8.91,1539,2352,0.99,1
2238,59,Puja,Srivastava,NaN,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,+91 080 22289999,...,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,8.91,1540,2358,0.99,1
2239,59,Puja,Srivastava,NaN,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,+91 080 22289999,...,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,8.91,1541,2364,0.99,1

In [6]:
df.shape

(2240, 25)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerId         2240 non-null   int64
 1   FirstName          2240 non-null   object
 2   LastName           2240 non-null   object
 3   Company            380 non-null    object
 4   Address            2240 non-null   object
 5   City               2240 non-null   object
 6   State              1140 non-null   object
 7   Country            2240 non-null   object
 8   PostalCode         2088 non-null   object
 9   Phone              2202 non-null   object
 10  Fax                456 non-null    object
 11  Email              2240 non-null   object
 12  SupportRepId       2240 non-null   int64
 13  InvoiceId          2240 non-null   int64
 14  InvoiceDate        2240 non-null   datetime64[ns]
 15  BillingAddress     2240 non-null   object
 16  BillingCity        2240 non-null   object
 17  BillingState       1140 non-null   object
 18  BillingCountry     2240 non-null   object
 19  BillingPostalCode  2088 non-null   object
 20  Total              2240 non-null   float64
 21  InvoiceLineId      2240 non-null   int64
 22  TrackId            2240 non-null   int64
 23  UnitPrice          2240 non-null   float64
 24  Quantity           2240 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(6), object(16)
memory usage: 437.6+ KB

In [9]:
df.sample()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,...,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,InvoiceLineId,TrackId,UnitPrice,Quantity
716,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,...,1 Infinite Loop,Cupertino,CA,USA,95014,5.94,1376,1366,0.99,1

In [8]:
df.describe()

,CustomerId,SupportRepId,InvoiceId,InvoiceDate,Total,InvoiceLineId,TrackId,UnitPrice,Quantity
count,2240.000000,2240.000000,2240.000000,2240,2240.000000,2240.000000,2240.000000,2240.000000,2240.0
mean,29.974107,3.950000,206.868750,2011-06-25 13:42:12.857142784,9.307420,1120.500000,1717.734375,1.039554,1.0
min,1.000000,3.000000,1.000000,2009-01-01 00:00:00,0.990000,1.000000,1.000000,0.990000,1.0
25%,15.000000,3.000000,103.000000,2010-03-21 00:00:00,5.940000,560.750000,874.000000,0.990000,1.0
50%,30.000000,4.000000,207.000000,2011-06-24 00:00:00,8.910000,1120.500000,1708.000000,0.990000,1.0
75%,45.000000,5.000000,311.000000,2012-09-28 00:00:00,13.860000,1680.250000,2560.000000,0.990000,1.0
max,59.000000,5.000000,412.000000,2013-12-22 00:00:00,25.860001,2240.000000,3500.000000,1.990000,1.0
std,17.018715,0.811485,119.134877,NaN,5.115131,646.776623,993.797999,0.217069,0.0

In [10]:
df.describe(include="O")

,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode
count,2240,2240,380,2240,2240,1140,2240,2088,2202,456,2240,2240,2240,1140,2240,2088
unique,57,59,10,59,53,25,24,55,58,12,59,59,53,25,24,55
top,Frank,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",Prague,SP,USA,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,"Av. Brigadeiro Faria Lima, 2170",Prague,SP,USA,12227-000
freq,76,38,38,38,76,114,494,38,38,38,38,38,76,114,494,38

In [15]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.isna().sum()

CustomerId              0
FirstName               0
LastName                0
Company              1860
Address                 0
City                    0
State                1100
Country                 0
PostalCode            152
Phone                  38
Fax                  1784
Email                   0
SupportRepId            0
InvoiceId               0
InvoiceDate             0
BillingAddress          0
BillingCity             0
BillingState         1100
BillingCountry          0
BillingPostalCode     152
Total                   0
InvoiceLineId           0
TrackId                 0
UnitPrice               0
Quantity                0
dtype: int64

In [21]:
df["Company"] = df["Company"] .fillna("unknown")
df["State"] = df["State"] .fillna("unknown")
df["PostalCode"] = df["PostalCode"] .fillna("unknown")
df["Phone"] = df["Phone"] .fillna("unknown")
df["Fax"] = df["Fax"] .fillna("unknown")
df["BillingState"] = df["BillingState"] .fillna("unknown")
df["BillingPostalCode"] = df["BillingPostalCode"] .fillna("unknown")

In [22]:
df.isna().sum()

CustomerId           0
FirstName            0
LastName             0
Company              0
Address              0
City                 0
State                0
Country              0
PostalCode           0
Phone                0
Fax                  0
Email                0
SupportRepId         0
InvoiceId            0
InvoiceDate          0
BillingAddress       0
BillingCity          0
BillingState         0
BillingCountry       0
BillingPostalCode    0
Total                0
InvoiceLineId        0
TrackId              0
UnitPrice            0
Quantity             0
dtype: int64

In [28]:
df["year_invoice"] = df["InvoiceDate"].dt.year
df["month_invoice"] = df["InvoiceDate"].dt.month
df["day_invoice"] = df["InvoiceDate"].dt.day_name()

In [30]:
df["year_invoice"].value_counts()

year_invoice
2010    455
2009    454
2012    447
2011    442
2013    442
Name: count, dtype: int64

# KPI Questions

# total output

In [36]:
df["Total"].sum().round(2)

np.float64(20848.62)

# No.of customers

In [37]:
df['CustomerId'].nunique()

59

# No.of invoices

In [38]:
df['InvoiceId'].nunique()

412

In [41]:
df.groupby('CustomerId')['InvoiceId'].nunique().mean()

np.float64(6.983050847457627)

# Top 10 customers in terms of revenue?

In [94]:
top_10_customers = df.groupby(['CustomerId','FirstName','LastName'])['Total'].sum().sort_values(ascending=False).head(10).reset_index()
top_10_customers

   CustomerId  FirstName     LastName       Total
0           6     Helena         Holý  502.620008
1          26    Richard   Cunningham  474.620008
2          46       Hugh     O'Reilly  446.620008
3          45   Ladislav       Kovács  446.620008
4          57       Luis        Rojas  415.619994
5          25     Victor      Stevens  404.620008
6           7     Astrid       Gruber  404.620008
7          37       Fynn   Zimmermann  388.619994
8          24      Frank      Ralston  378.619994
9           5  František  Wichterlová  376.620008

In [97]:
fig_top_10_customers = px.bar(top_10_customers,x="CustomerId",y="Total",text_auto=True,title=("top10 customers by revenue"))
fig_top_10_customers.show()

# less 10 customers in terms of revenue?

In [65]:
less_10_customers = df.groupby('CustomerId')['Total'].sum().sort_values(ascending=False).tail(10).reset_index()
less_10_customers

   CustomerId       Total
0          33  334.619994
1          47  334.619994
2          50  334.619994
3          49  334.619994
4          52  334.619994
5          53  334.619994
6          55  334.619994
7          54  334.619994
8          56  334.619994
9          59  331.659994

# Top 10 countries in terms of revenue?¶

In [50]:
top_10_Country = df.groupby('BillingCountry')['Total'].sum().sort_values(ascending=False).head(10).reset_index()
top_10_Country

   BillingCountry        Total
0             USA  4667.059951
1          Canada  2689.959955
2          France  1722.099985
3          Brazil  1677.099972
4         Germany  1392.479978
5  United Kingdom  1003.859983
6  Czech Republic   879.240016
7        Portugal   687.239989
8           India   667.279989
9         Ireland   446.620008

In [51]:
fig_top_10_Country = px.bar(top_10_Country,x="BillingCountry",y="Total",title=("Top 10 countries in terms of revenue"),text_auto=True)
fig_top_10_Country.show()

# total revenue by year

In [53]:
Year_revenue = df.groupby('year_invoice')['Total'].sum().reset_index()
Year_revenue

   year_invoice        Total
0          2009  4011.479933
1          2010  4329.449960
2          2011  4126.399961
3          2012  4256.249971
4          2013  4125.039946

In [56]:
fig_Year_revenue = px.bar(Year_revenue,x="year_invoice",y="Total",title=("total revenue by year"),text_auto=True)
fig_Year_revenue

# total revenue by month

In [57]:
month_revenue = df.groupby('month_invoice')['Total'].sum().reset_index()
month_revenue

    month_invoice        Total
0               1  1826.139985
1               2  1734.619985
2               3  1718.099972
3               4  1831.179985
4               5  1743.099985
5               6  1742.099969
6               7  1691.099972
7               8  1813.099985
8               9  1694.919984
9              10  1733.099985
10             11  1647.059990
11             12  1674.099972

In [58]:
fig_month_revenue = px.line(month_revenue,x="month_invoice",y="Total",title=("total revenue of month"),markers=True)
fig_month_revenue.show()

# total revenue by day_name

In [63]:
day_revenue = df.groupby('day_invoice')['Total'].sum().reset_index()
day_revenue

  day_invoice        Total
0      Friday  2845.629951
1      Monday  2878.979967
2    Saturday  3002.639964
3      Sunday  3130.909977
4    Thursday  2946.749982
5     Tuesday  2837.789951
6   Wednesday  3205.919977

In [64]:
fig_day_revenue = px.line(day_revenue,x="day_invoice",y="Total",title=("total revenue of day"),markers=True)
fig_day_revenue.show()

# average lifetime value of a customer?

In [71]:
 df.groupby('CustomerId')['Total'].sum().mean().round(2)

np.float64(353.37)

# average number of products on invoice

In [75]:
df.groupby('InvoiceId')['Quantity'].sum().mean()

np.float64(5.436893203883495)

# Total quantity per invoiceid

In [103]:
df.groupby("InvoiceId")["Quantity"].sum()

InvoiceId
1       2
2       4
3       6
4       9
5      14
       ..
408     4
409     6
410     9
411    14
412     1
Name: Quantity, Length: 412, dtype: int64

# total revenue , quantity by each country

In [87]:
country_revenue=df.groupby('BillingCountry').agg({
    'Quantity':'sum',
    'Total':'sum'
}).reset_index().sort_values(by="Total",ascending=False)
country_revenue

    BillingCountry  Quantity        Total
22             USA       494  4667.059951
5           Canada       304  2689.959955
10          France       190  1722.099985
4           Brazil       190  1677.099972
11         Germany       152  1392.479978
23  United Kingdom       114  1003.859983
7   Czech Republic        76   879.240016
19        Portugal        76   687.239989
13           India        74   667.279989
14         Ireland        38   446.620008
12         Hungary        38   446.620008
6            Chile        38   415.619994
2          Austria        38   404.620008
17          Norway        38   362.619994
16     Netherlands        38   352.619992
9          Finland        38   350.619994
21          Sweden        38   340.619994
1        Australia        38   334.619994
3          Belgium        38   334.619994
0        Argentina        38   334.619994
15           Italy        38   334.619994
8          Denmark        38   334.619994
18          Poland        38   334.619994
20           Spain        38   334.619994

In [91]:
fig_country_revenue = px.bar(df.groupby("BillingCountry")["Total"].sum().reset_index().sort_values(by="Total",ascending=False),x="BillingCountry",y="Total",text_auto=True,title=("total revenue by each country"))
fig_country_revenue.show()

In [93]:
fig_country_quantity = px.bar(df.groupby("BillingCountry")["Quantity"].sum().reset_index().sort_values(by="Quantity",ascending=False),x="BillingCountry",y="Quantity",text_auto=True,title=("total quantity by each country "))
fig_country_quantity.show()

#  all invoices along with the number of items in each invoice.

In [108]:
df.groupby("InvoiceId")["InvoiceLineId"].count().sort_values(ascending=False)

InvoiceId
411    14
404    14
376    14
383    14
26     14
33     14
341    14
47     14
362    14
369    14
Name: InvoiceLineId, dtype: int64