In [10]:
import pyodbc
import numpy as np 
import pandas as pd

In [12]:
connect = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                         'server=DESKTOP-C8VL8BV;'
                         'database=Customer;'
                         'trusted_connection=yes;'

)

In [13]:
connect

# 1. Retrieve all records from the Customer table.

In [37]:
df1 = pd.read_sql("SELECT * FROM Customer", connect)
df1.head()

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\2659885592.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql("SELECT * FROM Customer", connect)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [38]:
df2 = pd.read_sql("select * from Invoice", connect)
df2

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\4092482425.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql("select * from Invoice", connect)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02,Ullevålsveien 14,Oslo,None,Norway,171,3.96
2,3,8,2009-01-03,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2009-01-06,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05,319 N. Frances Street,Madison,WI,USA,53703,3.96
408,409,29,2013-12-06,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
409,410,35,2013-12-09,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
410,411,44,2013-12-14,Porthaninkatu 9,Helsinki,None,Finland,530,13.86
411,412,58,2013-12-22,"12,Community Centre",Delhi,None,India,110017,1.99

In [39]:
df3= pd.read_sql("select * from InvoiceLine", connect)
df3

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\1360340032.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df3= pd.read_sql("select * from InvoiceLine", connect)

      InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0                 1          1        2       0.99         1
1                 2          1        4       0.99         1
2                 3          2        6       0.99         1
3                 4          2        8       0.99         1
4                 5          2       10       0.99         1
...             ...        ...      ...        ...       ...
2235           2236        411     3136       0.99         1
2236           2237        411     3145       0.99         1
2237           2238        411     3154       0.99         1
2238           2239        411     3163       0.99         1
2239           2240        412     3177       1.99         1

[2240 rows x 5 columns]

# --2. Retrieve all invoices for a specific customer.

In [23]:
pd.read_sql("select *from Invoice where CustomerID = 20", connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\1867641386.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("select *from Invoice where CustomerID = 20", connect)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,113,20,2010-05-12,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,1.98
1,124,20,2010-06-22,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,13.86
2,179,20,2011-02-20,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,8.91
3,308,20,2012-09-26,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,3.98
4,331,20,2012-12-29,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,3.96
5,353,20,2013-04-02,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,5.94
6,405,20,2013-11-21,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,0.99

# --3. List all invoice lines along with their corresponding invoice and customer information.

In [24]:
pd.read_sql("select Invoice.InvoiceId ,Invoice.Total ,Invoice.InvoiceDate,Customer.CustomerId,Customer.FirstName,Customer.LastName from Customer join Invoice on Invoice.CustomerId = Customer.CustomerId",
connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\291604484.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("select Invoice.InvoiceId ,Invoice.Total ,Invoice.InvoiceDate,Customer.CustomerId,Customer.FirstName,Customer.LastName from Customer join Invoice on Invoice.CustomerId = Customer.CustomerId",

     InvoiceId  Total InvoiceDate  CustomerId FirstName    LastName
0            1   1.98  2009-01-01           2    Leonie      Köhler
1            2   3.96  2009-01-02           4     Bjørn      Hansen
2            3   5.94  2009-01-03           8      Daan     Peeters
3            4   8.91  2009-01-06          14      Mark     Philips
4            5  13.86  2009-01-11          23      John      Gordon
..         ...    ...         ...         ...       ...         ...
407        408   3.96  2013-12-05          25    Victor     Stevens
408        409   5.94  2013-12-06          29    Robert       Brown
409        410   8.91  2013-12-09          35  Madalena     Sampaio
410        411  13.86  2013-12-14          44     Terhi  Hämäläinen
411        412   1.99  2013-12-22          58     Manoj      Pareek

[412 rows x 6 columns]

# --4. Calculate total invoice amount per customer.

In [35]:
pd.read_sql("select Customer.CustomerId,Customer.FirstName,Customer.LastName , sum(Invoice.Total) as total_invoice from Customer join Invoice on  Customer.CustomerId = Invoice.CustomerId group by Customer.CustomerId,Customer.FirstName,Customer.LastName",
connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\2284463118.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("select Customer.CustomerId,Customer.FirstName,Customer.LastName , sum(Invoice.Total) as total_invoice from Customer join Invoice on  Customer.CustomerId = Invoice.CustomerId group by Customer.CustomerId,Customer.FirstName,Customer.LastName",

    CustomerId  FirstName      LastName  total_invoice
0            1       Luís     Gonçalves      39.620000
1            2     Leonie        Köhler      37.620000
2            3   François      Tremblay      39.620000
3            4      Bjørn        Hansen      39.620000
4            5  František   Wichterlová      40.620001
5            6     Helena          Holý      49.620001
6            7     Astrid        Gruber      42.620001
7            8       Daan       Peeters      37.620000
8            9       Kara       Nielsen      37.620000
9           10    Eduardo       Martins      37.620000
10          11  Alexandre         Rocha      37.620000
11          12    Roberto       Almeida      37.620000
12          13   Fernanda         Ramos      37.620000
13          14       Mark       Philips      37.620000
14          15   Jennifer      Peterson      38.620000
15          16      Frank        Harris      37.620000
16          17       Jack         Smith      39.620000
17          18   Michelle        Brooks      37.620000
18          19        Tim         Goyer      38.620000
19          20        Dan        Miller      39.620000
20          21      Kathy         Chase      37.620000
21          22    Heather       Leacock      39.620000
22          23       John        Gordon      37.620000
23          24      Frank       Ralston      43.620000
24          25     Victor       Stevens      42.620001
25          26    Richard    Cunningham      47.620001
26          27    Patrick          Gray      37.620000
27          28      Julia       Barnett      43.619999
28          29     Robert         Brown      37.620000
29          30     Edward       Francis      37.620000
30          31     Martha          Silk      37.620000
31          32      Aaron      Mitchell      37.620000
32          33      Ellie      Sullivan      37.620000
33          34       João     Fernandes      39.620000
34          35   Madalena       Sampaio      37.620000
35          36     Hannah     Schneider      37.620000
36          37       Fynn    Zimmermann      43.620000
37          38     Niklas      Schröder      37.620000
38          39    Camille       Bernard      38.620000
39          40  Dominique      Lefebvre      38.620000
40          41       Marc        Dubois      37.620000
41          42      Wyatt        Girard      39.620000
42          43   Isabelle       Mercier      40.620001
43          44      Terhi    Hämäläinen      41.620000
44          45   Ladislav        Kovács      45.620001
45          46       Hugh      O'Reilly      45.620001
46          47      Lucas       Mancini      37.620000
47          48   Johannes  Van der Berg      40.619999
48          49  Stanisław        Wójcik      37.620000
49          50    Enrique         Muñoz      37.620000
50          51     Joakim     Johansson      38.620000
51          52       Emma         Jones      37.620000
52          53       Phil        Hughes      37.620000
53          54      Steve        Murray      37.620000
54          55       Mark        Taylor      37.620000
55          56      Diego     Gutiérrez      37.620000
56          57       Luis         Rojas      46.620000
57          58      Manoj        Pareek      38.620000
58          59       Puja    Srivastava      36.640000

# --5. Retrieve the top 5 customers by total spending.

In [26]:
pd.read_sql("select top(5) Customer.CustomerId,Customer.FirstName,Customer.LastName , sum(Invoice.Total) as total_invoice from Customer join Invoice on  Customer.CustomerId = Invoice.CustomerId group by Customer.CustomerId,Customer.FirstName,Customer.LastName order by total_invoice desc",
connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\2069238392.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("select top(5) Customer.CustomerId,Customer.FirstName,Customer.LastName , sum(Invoice.Total) as total_invoice from Customer join Invoice on  Customer.CustomerId = Invoice.CustomerId group by Customer.CustomerId,Customer.FirstName,Customer.LastName order by total_invoice desc",

   CustomerId FirstName    LastName  total_invoice
0           6    Helena        Holý      49.620001
1          26   Richard  Cunningham      47.620001
2          57      Luis       Rojas      46.620000
3          45  Ladislav      Kovács      45.620001
4          46      Hugh    O'Reilly      45.620001

# --6. Count the number of invoices per customer.

In [36]:
pd.read_sql("select CustomerId,count(InvoiceID) as invoices_number from Invoice group by CustomerId order by invoices_number desc",
connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\2546033698.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("select CustomerId,count(InvoiceID) as invoices_number from Invoice group by CustomerId order by invoices_number desc",

    CustomerId  invoices_number
0            1                7
1            2                7
2            3                7
3            4                7
4            5                7
5            6                7
6            7                7
7            8                7
8            9                7
9           10                7
10          11                7
11          12                7
12          13                7
13          14                7
14          15                7
15          16                7
16          17                7
17          18                7
18          19                7
19          20                7
20          21                7
21          22                7
22          23                7
23          24                7
24          25                7
25          26                7
26          27                7
27          28                7
28          29                7
29          30                7
30          31                7
31          32                7
32          33                7
33          34                7
34          35                7
35          36                7
36          37                7
37          38                7
38          39                7
39          40                7
40          41                7
41          42                7
42          43                7
43          44                7
44          45                7
45          46                7
46          47                7
47          48                7
48          49                7
49          50                7
50          51                7
51          52                7
52          53                7
53          54                7
54          55                7
55          56                7
56          57                7
57          58                7
58          59                6

# --7. Calculate total quantity of tracks sold per invoice.

In [28]:
pd.read_sql("select InvoiceID,TrackId ,sum(Quantity) as total_quantity from InvoiceLine group by  InvoiceID , TrackId",
connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\678994190.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("select InvoiceID,TrackId ,sum(Quantity) as total_quantity from InvoiceLine group by  InvoiceID , TrackId",

      InvoiceID  TrackId  total_quantity
0           108        1               1
1             1        2               1
2           214        2               1
3           319        3               1
4             1        4               1
...         ...      ...             ...
2235        319     3494               1
2236        108     3496               1
2237        214     3499               1
2238        108     3500               1
2239        319     3500               1

[2240 rows x 3 columns]

# --8. Retrieve all invoices where the total amount exceeds $50.

In [31]:
pd.read_sql("select * from Invoice where Total > 50", connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\2022676433.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("select * from Invoice where Total > 50", connect)

Empty DataFrame
Columns: [InvoiceId, CustomerId, InvoiceDate, BillingAddress, BillingCity, BillingState, BillingCountry, BillingPostalCode, Total]
Index: []

# --9. Identify the customer who purchased the most tracks overall.

In [33]:
pd.read_sql("select Customer.CustomerId , sum(InvoiceLine.Quantity) as total_quantity from Customer join Invoice on Customer.CustomerId = Invoice.CustomerId join InvoiceLine on Invoice.Invoiceid = InvoiceLine.Invoiceid group by Customer.CustomerId order by sum(Invoice.Total) desc", connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\215829699.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("select Customer.CustomerId , sum(InvoiceLine.Quantity) as total_quantity from Customer join Invoice on Customer.CustomerId = Invoice.CustomerId join InvoiceLine on Invoice.Invoiceid = InvoiceLine.Invoiceid group by Customer.CustomerId order by sum(Invoice.Total) desc", connect)

    CustomerId  total_quantity
0            6              38
1           26              38
2           46              38
3           45              38
4           57              38
5            7              38
6           25              38
7           37              38
8           24              38
9            5              38
10          43              38
11          28              38
12           4              38
13          17              38
14          34              38
15          48              38
16          44              38
17          15              38
18          51              38
19          22              38
20          20              38
21           3              38
22           1              38
23          42              38
24          40              38
25          39              38
26          19              38
27          58              38
28          38              38
29          55              38
30          49              38
31          21              38
32          27              38
33          52              38
34          32              38
35          12              38
36          35              38
37           9              38
38          29              38
39          36              38
40          13              38
41          56              38
42          23              38
43          50              38
44          47              38
45          30              38
46          18              38
47          10              38
48          41              38
49          16              38
50          53              38
51          33              38
52           2              38
53          14              38
54          11              38
55          54              38
56          31              38
57           8              38
58          59              36

# --10. List all invoices along with the number of items in each invoice.

In [44]:
pd.read_sql("SELECT Invoice.InvoiceID,COUNT(InvoiceLine.InvoicelineID) AS number_of_items FROM invoice JOIN InvoiceLine on Invoice.InvoiceID = InvoiceLine.InvoiceID group by Invoice.InvoiceID", connect)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_15448\2324673732.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT Invoice.InvoiceID,COUNT(InvoiceLine.InvoicelineID) AS number_of_items FROM invoice JOIN InvoiceLine on Invoice.InvoiceID = InvoiceLine.InvoiceID group by Invoice.InvoiceID", connect)

     InvoiceID  number_of_items
0          261                4
1           23                4
2          238                2
3          355               14
4           46                9
..         ...              ...
407        151                9
408        194               14
409        200                9
410        100                4
411        343                2

[412 rows x 2 columns]

# merge tables

In [47]:
merged_df = df1.merge(df2, on='CustomerId', how='inner') \
               .merge(df3, on='InvoiceId', how='inner')
merged_df.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,...,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total,InvoiceLineId,TrackId,UnitPrice,Quantity
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,531,3247,1.99,1
1,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98,532,3248,1.99,1
2,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,649,447,0.99,1
3,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,650,449,0.99,1
4,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96,651,451,0.99,1

In [52]:
merged_df.to_excel("merged_output.xlsx", index=False)

In [53]:
import os
os.getcwd()

'C:\\Users\\LOQ'

In [49]:
merged_df.info()
merged_df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerId         2240 non-null   int64
 1   FirstName          2240 non-null   object
 2   LastName           2240 non-null   object
 3   Company            380 non-null    object
 4   Address            2240 non-null   object
 5   City               2240 non-null   object
 6   State              1140 non-null   object
 7   Country            2240 non-null   object
 8   PostalCode         2088 non-null   object
 9   Phone              2202 non-null   object
 10  Fax                456 non-null    object
 11  Email              2240 non-null   object
 12  SupportRepId       2240 non-null   int64
 13  InvoiceId          2240 non-null   int64
 14  InvoiceDate        2240 non-null   datetime64[ns]
 15  BillingAddress     2240 non-null   object
 16  BillingCity        2240 non-null   object
 17  BillingState       1140 non-null   object
 18  BillingCountry     2240 non-null   object
 19  BillingPostalCode  2088 non-null   object
 20  Total              2240 non-null   float64
 21  InvoiceLineId      2240 non-null   int64
 22  TrackId            2240 non-null   int64
 23  UnitPrice          2240 non-null   float64
 24  Quantity           2240 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(6), object(16)
memory usage: 437.6+ KB

(2240, 25)

In [51]:
merged_df.isna().sum()

CustomerId              0
FirstName               0
LastName                0
Company              1860
Address                 0
City                    0
State                1100
Country                 0
PostalCode            152
Phone                  38
Fax                  1784
Email                   0
SupportRepId            0
InvoiceId               0
InvoiceDate             0
BillingAddress          0
BillingCity             0
BillingState         1100
BillingCountry          0
BillingPostalCode     152
Total                   0
InvoiceLineId           0
TrackId                 0
UnitPrice               0
Quantity                0
dtype: int64

In [54]:
connect.close()